# Generated by Django 3.0.4 on 2020-07-09 17:23

from django.db import migrations, models
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.FloatField(null=True, verbose_name='popularity')),
                ('genre', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, size=10)),
                ('imdb_score', models.FloatField(verbose_name='imdb_score')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
            ],
        ),
    ]
