# Generated by Django 3.0.4 on 2020-07-10 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.FloatField(db_column='99popularity', null=True)),
                ('director', models.CharField(max_length=300, verbose_name='director')),
                ('genre', models.CharField(max_length=300, verbose_name='genre')),
                ('imdb_score', models.FloatField(verbose_name='imdb_score')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
            ],
        ),
    ]
